#!/usr/bin/env tsx
/**
 * tldraw-dev — Build tldraw from source and link it into BigBlueButton.
 *
 * Usage:
 *   yarn dev-bbb [setup|rebuild|watch|show] [-b <path>] [-c <path>]
 *
 * Resolution priority (highest → lowest):
 *   1. --bbb-html5 argument
 *   2. BBB_HTML5_DIR environment variable
 *   3. BBB_HTML5_DIR in config file  (default: <tldraw-root>/.tldraw-dev.conf)
 *   4. ../../bigbluebutton/bigbluebutton-html5  (relative to this repo)
 */

import { execSync } from 'child_process'
import chokidar from 'chokidar'
import { Command } from 'commander'
import fs from 'fs'
import ora from 'ora'
import os from 'os'
import path from 'path'

// ── Constants ─────────────────────────────────────────────────────────────────

const TLDRAW_ROOT = path.resolve(__dirname, '..')
const TLDRAW_PKG_DIR = path.join(TLDRAW_ROOT, 'packages/tldraw')
const BUILD_INFO_FILE = path.join(TLDRAW_PKG_DIR, 'src/lib/buildInfo.ts')
const DEFAULT_CONFIG_FILE = path.join(TLDRAW_ROOT, '.tldraw-dev.conf')
const WEBPACK_ENTRY = path.join('imports/ui/components/whiteboard/component.jsx')

// Ensure nvm-managed binaries (yalc, yarn) are reachable from child processes
const nvmBin = path.join(os.homedir(), `.nvm/versions/node/${process.version.replace('v', '')}/bin`)
if (fs.existsSync(nvmBin)) process.env.PATH = `${nvmBin}:${process.env.PATH ?? ''}`

// ── Config file ───────────────────────────────────────────────────────────────

function loadConfigFile(configFile: string): string | undefined {
	if (!fs.existsSync(configFile)) return undefined
	for (const line of fs.readFileSync(configFile, 'utf8').split('\n')) {
		const match = line.match(/^BBB_HTML5_DIR=(.+)$/)
		if (match) return match[1].trim().replace(/^['"]|['"]$/g, '')
	}
	return undefined
}

// ── Path resolution ───────────────────────────────────────────────────────────

// Chain of responsibility: each source is checked in priority order.
// First non-empty source wins; the last resort verifies the default path exists.
function resolveBbbHtml5Dir(
	paramHtml5: string | undefined,
	configFile: string
): { dir: string; source: string } {
	if (paramHtml5) return { dir: paramHtml5, source: '--bbb-html5 argument' }

	if (process.env.BBB_HTML5_DIR)
		return { dir: process.env.BBB_HTML5_DIR, source: 'BBB_HTML5_DIR env var' }

	const confVal = loadConfigFile(configFile)
	if (confVal) return { dir: confVal, source: `config file (${configFile})` }

	const defaultDir = path.resolve(TLDRAW_ROOT, '../bigbluebutton/bigbluebutton-html5')
	if (!fs.existsSync(defaultDir)) {
		console.error(
			`\nERROR: bigbluebutton-html5 not found.\n` +
				`  Pass --bbb-html5 <path>, set $BBB_HTML5_DIR, ` +
				`or add BBB_HTML5_DIR to ${configFile}.\n`
		)
		process.exit(1)
	}
	return { dir: defaultDir, source: 'default sibling path' }
}

// ── Build steps — each function has one responsibility ────────────────────────

function writeBuildInfo(buildId: string): void {
	const s = ora(`Generating build ID`).start()
	fs.writeFileSync(
		BUILD_INFO_FILE,
		[
			'// Generated by scripts/tldraw-dev.ts — do not edit manually',
			'/** @internal */',
			`export const TLDRAW_BUILD_ID = '${buildId}';`,
			`console.log('[tldraw] build_id: ' + TLDRAW_BUILD_ID);`,
			'',
		].join('\n')
	)
	s.succeed(`Build ID: ${buildId}`)
}

function buildPackage(): void {
	const s = ora('Building tldraw (types → api → bundle)').start()
	s.stop()
	execSync('yarn run -T lazy build --filter packages/tldraw', {
		cwd: TLDRAW_ROOT,
		stdio: 'inherit',
	})
	s.succeed('tldraw package built')
}

function publishToYalc(): void {
	const s = ora('Publishing to local yalc store').start()
	s.stop()
	execSync('yalc publish', { cwd: TLDRAW_PKG_DIR, stdio: 'inherit' })
	s.succeed('Published to yalc store')
}

function relinkInBBB(bbbHtml5Dir: string): void {
	const s = ora('Relinking @bigbluebutton/tldraw').start()
	s.stop()
	try {
		execSync('yalc remove @bigbluebutton/tldraw', { cwd: bbbHtml5Dir, stdio: 'ignore' })
	} catch {
		// not yet linked — fine
	}
	execSync('yalc add @bigbluebutton/tldraw', { cwd: bbbHtml5Dir, stdio: 'inherit' })
	execSync('npm install --prefer-offline --no-audit --no-fund', {
		cwd: bbbHtml5Dir,
		stdio: 'inherit',
	})

	s.succeed('@bigbluebutton/tldraw relinked')
}

function triggerWebpackRebuild(bbbHtml5Dir: string): void {
	const s = ora('Triggering webpack rebuild').start()
	const now = new Date()
	fs.utimesSync(path.join(bbbHtml5Dir, WEBPACK_ENTRY), now, now)
	s.succeed('Webpack rebuild triggered')
}

// ── Orchestrator — single responsibility: coordinate the build pipeline ───────

function buildAndLink(bbbHtml5Dir: string): void {
	const buildId = `build-${Date.now()}`
	writeBuildInfo(buildId)
	buildPackage()
	publishToYalc()
	relinkInBBB(bbbHtml5Dir)
	triggerWebpackRebuild(bbbHtml5Dir)
	console.log(`\nTLDRAW_BUILD_ID=${buildId}`)
}

// ── Watch ─────────────────────────────────────────────────────────────────────

function watchForChanges(bbbHtml5Dir: string): void {
	const watchDir = path.join(TLDRAW_PKG_DIR, 'src')
	let rebuilding = false

	const idle = ora(`Watching ${watchDir} for changes`).start()

	const watcher = chokidar
		.watch(watchDir, {
			ignored: [/buildInfo\.ts$/, /\.test\.[^/]+$/, /__tests__/],
			ignoreInitial: true,
			awaitWriteFinish: { stabilityThreshold: 300, pollInterval: 100 },
		})
		.on('all', () => {
			if (rebuilding) return
			rebuilding = true
			idle.stop()
			console.log('\nChange detected, rebuilding...')
			try {
				buildAndLink(bbbHtml5Dir)
			} catch (err) {
				console.error('Rebuild failed:', err)
			}
			rebuilding = false
			idle.start(`Watching ${watchDir} for changes`)
		})

	process.on('SIGINT', () => {
		idle.stop()
		watcher.close()
		process.exit(0)
	})
}

// ── CLI ───────────────────────────────────────────────────────────────────────

const program = new Command()
	.name('tldraw-dev')
	.description(
		'Build tldraw from source and link it into BigBlueButton.\n\n' +
			'Resolution priority (highest → lowest):\n' +
			'  1. --bbb-html5 argument\n' +
			'  2. BBB_HTML5_DIR environment variable\n' +
			'  3. BBB_HTML5_DIR in config file (.tldraw-dev.conf)\n' +
			'  4. ../../bigbluebutton/bigbluebutton-html5 (default)'
	)
	.option('-b, --bbb-html5 <path>', 'Path to bigbluebutton-html5 (highest priority)')
	.option('-c, --config <path>', 'Config file path', DEFAULT_CONFIG_FILE)

type GlobalOpts = { bbbHtml5?: string; config: string }

function resolveDir() {
	const { bbbHtml5, config } = program.opts<GlobalOpts>()
	return resolveBbbHtml5Dir(bbbHtml5, config)
}

function printHeader(dir: string, source: string): void {
	console.log(`tldraw root : ${TLDRAW_ROOT}`)
	console.log(`bbb html5   : ${dir}`)
	console.log(`source      : ${source}\n`)
}

const buildAction = () => {
	const { dir, source } = resolveDir()
	printHeader(dir, source)
	buildAndLink(dir)
}

program
	.command('setup', { isDefault: true })
	.description('Initial build and link (default command)')
	.action(buildAction)

program
	.command('rebuild')
	.description('Rebuild tldraw and relink into BigBlueButton')
	.action(buildAction)

program
	.command('watch')
	.description('Build, link, then watch src/ and rebuild on every change')
	.action(() => {
		const { dir, source } = resolveDir()
		printHeader(dir, source)
		buildAndLink(dir)
		watchForChanges(dir)
	})

// show: machine-readable output used by tests and debugging — no spinners
program
	.command('show')
	.description('Print resolved paths without building')
	.action(() => {
		const { dir, source } = resolveDir()
		console.log(`tldraw-root=${TLDRAW_ROOT}`)
		console.log(`bbb-html5=${dir}`)
		console.log(`bbb-html5-source=${source}`)
	})

program.parse()
